apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vllm.yaml
configMapGenerator:
  - name: vllm-model-bootstrap
    namespace: crossscale
    files:
      - download-model.sh
      - model-snapshot.tsv
