apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deploy
replicas:
  - name: vllm
    count: 1
patches:
  - target:
      kind: Deployment
      name: vllm
    patch: |-
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 2400
      - op: add
        path: /spec/strategy
        value:
          type: Recreate
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - /models/llama
          - --served-model-name
          - meta-llama/Llama-3.1-8B-Instruct
          - --max-model-len
          - '4096'
          - --max-num-seqs
          - '4'
          - --gpu-memory-utilization
          - '0.90'
          - --enforce-eager
